### ISSUE TITLE
my vapoursynth plugin "knlmeanscl" doesn't work and keeps giving me the same errors. please help

### ISSUE THREAD

**Issue by viliobloom** [Khanattila/KNLMeansCL#45]
hello! i have an issue with one of the denoisers in vapoursynth and despite everything i've tried doing it doesn't seem to work. i have looked through your account and there was someone with a similar issue to mine but another account suggested the problem could be from both of our vapoursynths not having a certain plugin in which is the knlm that was linked back to your account. my problem is whenever i try to use the knlm denoise it keeps giving me the same error message in the log, read: "Failed to evaluate the script:
Python exception: No attribute with the name knlm exists. Did you mistype a plugin namespace?

Traceback (most recent call last):
File "src\cython\vapoursynth.pyx", line 1927, in vapoursynth.vpy_evaluateScript
File "src\cython\vapoursynth.pyx", line 1928, in vapoursynth.vpy_evaluateScript
File "C:/Users/user/Downloads/VapourSynth64Portable/gifs/script.vpy", line 20, in 
File "src\cython\vapoursynth.pyx", line 1522, in vapoursynth.Core.__getattr__
AttributeError: No attribute with the name knlm exists. Did you mistype a plugin namespace?"

I have tried googling, i have downloaded the plugin folder from hackmd's tutorial on vapoursynth but i still can't use the knlm denoiser. i would really like to use this but i simply cannot figure out how, please help me.

**Comment by Khanattila** [comment]
Hi @viliobloom, I'm sorry for your problem but from the log file seems like that vapoursynth does not load the plugin.  So I invite you to check that you have put the correct DLL in the right place. 
If it doesn't solve it, I invite you to share the details of your system.
