### ISSUE TITLE
VapourSynth: device_type="cpu" throws "no compatible opencl platforms available!"

### ISSUE THREAD

**Issue by mysteryx93** [Khanattila/KNLMeansCL#51]
With KNLMeansCL in VapourSynth, if I set device_type="cpu", it throws: "no compatible opencl platforms available!"

**Comment by brucethemoose** [comment]
If you are on linux, this may be related to https://github.com/Khanattila/KNLMeansCL/issues/55

Now it wont even start when I have pocl installed:

```
Traceback (most recent call last):
File "src/cython/vapoursynth.pyx", line 2866, in vapoursynth._vpy_evaluate
File "src/cython/vapoursynth.pyx", line 2867, in vapoursynth._vpy_evaluate
File "/home/alpha/Storage/clone/StableDiffusion-Video2Video/SDtest.vpy", line 13, in 
clip = core.knlm.KNLMeansCL(clip, d=2, a=3)
File "src/cython/vapoursynth.pyx", line 2612, in vapoursynth.Function.__call__
vapoursynth.Error: knlm.KNLMeansCL: fatal error!
(oclUtilsGetPlaformDeviceIDs: CL_INVALID_VALUE)
```
Output from the ocl library:
```
OpenCL: File locking mechanism enabled. Will probably fail if run under a queueing system.
-------------------------------------------------------------------------------------------------------------
OpenCL: Getting a list of platform(s)... done.
OpenCL: Initializing the 4 available platforms...
        (1/4) NVIDIA Corporation
        (2/4) Mesa
        (3/4) Mesa/X.org
        (4/4) The pocl project
OpenCL: Initialize platform "NVIDIA CUDA"'s device(s)
OpenCL: WARNING: Can't find a usable CPU!
OpenCL: Attempt to acquire lock on file /tmp/OpenCL_Platform0_Device0__NVIDIA_CUDA_NVIDIA_GeForce_RTX_2060_with_Max_Q_Design.lck...Success!
ERROR: Unknown OpenCL platform "mesa"! Exiting.
fish: Job 1, './OclUtilsExample' terminated by signal SIGABRT (Abort)
```

**Comment by metagondria** [comment]
> With KNLMeansCL in VapourSynth, if I set device_type="cpu", it throws: "no compatible opencl platforms available!"

I have moved over to an new build (Ryzen AMD) , and i have the same problem when i set type = cpu in Hybrid video encoder software by selur !!

When set to gpu or auto, it works just ok.. But i have much less FPS using only gpu !!  Using NLmeans in vidcoder in full cpu mode offers me like 3 or 4 times more fps !!!

I have tried to replace .dll file/version but it didn't helped !!

I know, it's meant to use only GPU accelerated hardware...  But i like to use it in CPU (non-igpu) Mode only !!
Is there an fix in progress ?  any One ?

cheers,

**Comment by ted423** [comment]
cpu need opencl runtime, but it's too slow to use

**Comment by ted423** [comment]
like this https://www.intel.com/content/www/us/en/developer/articles/tool/opencl-drivers.html
